name: Development SSH Connection and Deploy to Server

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: /common-workflows/.github/workflows/nestjs-ssh-connection-and-deploy-to-server.yml@main
    with:
      container-uri: ${{ vars.DEV_CONTAINER_URI }}
      node-env: dev
    secrets: inherit